name: Build, Migrate, Backup, and Deploy .NET Core API

on:
  push:
    branches:
      - master

jobs:
  build-migrate-deploy:
    runs-on: ubuntu-latest

    env:
      DOTNET_VERSION: '8.0.x'  # Adjust to your target version
      RUNTIME_ID: linux-x64    # Change to win-x64 or linux-arm if needed
      PUBLISH_DIR: ./publish
      BACKUP_FOLDER: backup_$(date +'%Y%m%d_%H%M%S')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      
      - name: Publish self-contained build
        run: |
          dotnet publish -c Release -r ${{ env.RUNTIME_ID }} --self-contained true -o ${{ env.PUBLISH_DIR }}

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Backup existing deployment from FTP
        run: |
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
            set ssl:verify-certificate no;
            mkdir -p /backups/${{ env.BACKUP_FOLDER }};
            mirror --verbose /public_html/api /backups/${{ env.BACKUP_FOLDER }};
            bye
          "

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: eu-central-1.sftpcloud.io #${{ secrets.FTP_HOST }}
          username: 1b2cc285bcc24652bd56c9136f9f688f #${{ secrets.FTP_USERNAME }}
          password: OgmMFXM1yFIeuU1TCAGrOA39XlHxJdbu #${{ secrets.FTP_PASSWORD }}
          local-dir: ${{ env.PUBLISH_DIR }}
          server-dir: /public_html/api/
          protocol: ftp
          exclude: |
            **/.git*
            **/.github*
            **/obj/**
            **/bin/**
